SELECT * FROM customers
SELECT * FROM order_details
SELECT * FROM orders
SELECT * FROM pizza_types
SELECT * FROM pizzas


-- 1. List all pizzas with a price greater than $15.
SELECT * FROM pizzas 
WHERE price>15

-- 2. Find the total number of customers in the database.
SELECT COUNT(*) AS total
FROM customers

-- 3. List all distinct pizza categories.
SELECT DISTINCT category 
FROM pizza_types

-- 4. Find the total revenue generated from all orders.
SELECT SUM(od.quantity * p.price) AS total_revenue
FROM order_details od
JOIN pizzas p ON od.pizza_id = p.pizza_id;

-- 5. Find the top 5 most ordered pizza types by total quantity sold.
SELECT pt.name, SUM(od.quantity) AS total_quantity
FROM order_details od
JOIN pizzas p ON od.pizza_id = p.pizza_id
JOIN pizza_types pt ON p.pizza_type_id = pt.pizza_type_id
GROUP BY pt.name
ORDER BY total_quantity DESC
LIMIT 5;

-- 6. Find the average price of pizzas in each category.
SELECT pt.category, ROUND(AVG(p.price), 2) AS avg_price
FROM pizzas p
JOIN pizza_types pt ON p.pizza_type_id = pt.pizza_type_id
GROUP BY pt.category
ORDER BY avg_price DESC;

-- 7. List the total number of orders placed each month in 2023.
SELECT EXTRACT(MONTH FROM order_date) AS month,
       COUNT(*) AS total_orders
FROM orders
WHERE EXTRACT(YEAR FROM order_date) = 2023
GROUP BY month
ORDER BY month;

-- 8. Find the customer who has placed the most orders.
SELECT o.customer_id, SUM(od.quantity * p.price) AS total_spent
FROM orders o
JOIN order_details od ON o.order_id = od.order_id
JOIN pizzas p ON od.pizza_id = p.pizza_id
GROUP BY o.customer_id
ORDER BY total_spent DESC
LIMIT 3;

-- 9. Find the top 3 customers by total amount spent.

-- 10. Find the percentage contribution of each pizza category to total revenue.
SELECT pt.category,
       ROUND(
         SUM(od.quantity * p.price) * 100.0
         / SUM(SUM(od.quantity * p.price)) OVER (), 2
       ) AS pct_of_revenue
FROM order_details od
JOIN pizzas p ON od.pizza_id = p.pizza_id
JOIN pizza_types pt ON p.pizza_type_id = pt.pizza_type_id
GROUP BY pt.category
ORDER BY pct_of_revenue DESC;

-- 11. Which day of the week has the highest number of orders?

-- 12. Compare revenue generated by "Completed" vs "Cancelled" vs "Refunded" orders.
